= Contributing to the Deliverance
Tunggul Hutagalung
:icons: font
:toc: left
:toc-title: Contents
:toclevels: 4
:code-of-conduct: link:CODE_OF_CONDUCT.adoc
:service-email: code-of-conduct@jirehsoft.com
:issue-tracker: https://github.com/deliverance/repo-crawler/issues
:rewrite-history: https://git-scm.com/book/en/Git-Tools-Rewriting-History
:commit-guideline: https://git-scm.com/book/en/Distributed-Git-Contributing-to-a-Project=Commit-Guidelines
:build-from-source: https://github.com/deliverance/repo-crawler/src/master/README.adoc
:code-style: https://jirehsoft.com//wiki/code-style
:ide-settings: https://jirehsoft.com/wiki/ide-settings
:asciidoc-url: https://asciidoctor.org/
:asciidoc-live-preview: https://asciidoctor.org/docs/editing-asciidoc-with-live-preview/
:system-monitor: https://asciidoctor.org/docs/editing-asciidoc-with-live-preview/=using-a-system-monitor

== Welcome

First off, thank you for taking the time to contribute! icon:thumbs-up[]

== Code of Conduct

This project is governed by the <<_code_of_conduct, JirehSoft Code of Conduct>>.
By participating you are expected to uphold this code.
Please report unacceptable behavior to {service-email}.

== How to Contribute

=== Discuss

If you suspect an issue, perform a search in the {issue-tracker}[GitHub issue tracker], using a few different keywords.
When you find related issues and discussions, prior or current, it helps you to learn and it helps us to make 
a decision.

=== Create a Ticket

Reporting an issue or making a feature request is a great way to contribute.
Your feedback and the conversations that result from it provide a continuous flow of ideas.

Before you create a ticket, please take the time to research first.

If creating a ticket after a discussion, please provide a self-sufficient description in the ticket, independent 
of the details. We understand this is extra work but the issue tracker is an important place of record for design 
discussions and decisions that can often be referenced long after the fix version, for example to revisit decisions, 
to understand the origin of a feature, and so on.

When ready create a ticket in the {issue-tracker}[GitHub issue tracker].

=== Ticket Lifecycle

When an issue is first created, it may not be assigned and will not have a fix version.
Within a day or two, the issue is assigned to a specific committer and the target version is set 
to "Waiting for Triage".

The committer will then review the issue, ask for further information if needed, and based on the findings, 
the issue is either assigned a fix version or rejected.

When a fix is ready, the issue is marked "Resolved" and may still be re-opened.
Once a fix is released, the issue is permanently "Closed".
If necessary, you will need to create a new, related ticket with a fresh description.

=== Submit a Pull Request

You can contribute a source code change by submitting a pull request.

. For all but the most trivial of contributions, please <<Create a Ticket, create a ticket>>.
The purpose of the ticket is to understand and discuss the underlying issue or feature.
We use the GitHub issue tracker as the preferred place of record for conversations and conclusions.
In that sense discussions directly under a PR are more implementation detail oriented and transient in nature.

. Always check out the `master` branch and submit pull requests against it.
Backports to prior versions will be considered on a case-by-case basis and reflected as the fix version in the 
issue tracker.

. Use short branch names, preferably based on the GitHub issue (e.g. `JIM-1234`), or otherwise using succinct, 
lower-case, dash (-) delimited names, such as `fix-warnings`.

. Choose the granularity of your commits consciously and squash commits that represent multiple edits or corrections 
of the same logical change.
See {rewrite-history}[Rewriting History section of Pro Git]
for an overview of streamlining commit history.

. Format commit messages using 55 characters for the subject line, 72 lines for the description, followed by 
related issues, e.g. `Issues: JIM-1234, JIM-1235`.
See the {commit-guideline}[Commit Guidelines section of Pro Git]
for best practices around commit messages and use `git log` to see some examples.

. List the GitHub issue number in the PR description.

If accepted, your contribution may be heavily modified as needed prior to merging.
You will likely retain author attribution for your Git commits granted that the bulk of your changes remain intact.
You may also be asked to rework the submission.

If asked to make corrections, simply push the changes against the same branch, and your pull request will be updated.
In other words, you do not need to create a new pull request when asked to make changes.

== Build from Source

See the {build-from-source}[build from source] for instructions on how to check out, build and import 
the repository-crawler source code into your IDE.

== Source Code Style

The wiki pages {code-style}[code style] and {ide-settings}[IDE settings] defines the source file coding standards 
we use along with some IDEA editor settings we customize.

== Reference Docs

The reference documentation is in the `src/docs/asciidoc` directory and in
{asciidoc-url}[Asciidoctor] format.

When making changes locally, use `./mvnw asciidoctor` and then browse the result under
`build/asciidoc/html5/index.html`.

Asciidoctor also supports live editing. For more details read {asciidoc-live-preview}[Editing AsciiDoc 
with Live Preview]. Note that if you choose the {system-monitor}[System Monitor] option, you can find 
a Guardfile under `src/docs/asciidoc`.
